### ISSUE TITLE
Issue with MSApplicationMetadata

### ISSUE THREAD

**Issue by oodesign** [mathieudutour/sketch-module-google-analytics#13]
Hi Mathieu!

Looks like Sketch 72 the MSApplicationMetadata class has been replaced by BCSketchInfo.
I see sketch-module-google-analytics is still using MSApplicationMetadata (and having some issues with it :) ).

Is there any plan to update the analytics module?

Thanks!

**Comment by mathieudutour** [comment]
I don't have any plan but I can merge a PR

**Comment by oodesign** [comment]
Cool! I'll take a look when I have a min :) 
Thanks!

**Comment by bomberstudios** [comment]
Opened a PR that fixes this
