### ISSUE TITLE
where the data like "&ds=sketch66" can be seen in google analytics?

### ISSUE THREAD

**Issue by Woohuang** [mathieudutour/sketch-module-google-analytics#6]
Sorry sir I have searched a lot but get nothing about where the data posted through this parameter "&ds=sketch66" can be seen in google analytics. So I'm here to look for your general help~. Actually I have send some event data successfully and I can find them in google analytics, but the data source still remains hidden for me. I have searched all the google and google analytics help doc, it gives me nothing. I‘m really curious about this, so can you give me some suggestion? Appreciate that a lot~

**Comment by mathieudutour** [comment]
I have no idea. I just used the parameter described here: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ds

I'm never actually checking analytics

**Comment by Woohuang** [comment]
thank you all the same ~
